### ISSUE TITLE
Make local setup for Uli seamless

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#296]
**Is your feature request related to a problem? Please describe.**
Whenever new joinees try to setup Uli, some pesky issues come up related to their platform or inconsistency in the documentation.

**Comment by dennyabrain** [comment]
Lets consolidate the 3 READMEs within `browser-extension` into one README. We can add sections pertaining to specific userflows within that README. So for instance, someone who is only working on the api-server might want to comment out the ogbv-ml-rest service from docker-compose. These instructions can go in those sections.

**Comment by duggalsu** [comment]
As per mysql docker notes, the `uli_dev` db should be created automatically on initializing the db container since the envvar specifying the db name is present. However, this is not happening.
- https://hub.docker.com/_/mysql/

Without this, the migration fails as it cannot find the db. Hence, `docker compose up` has to be run, the db has to be created manually and `docker compose up` has to be run again. The alternative is to specify an init db file
- https://stackoverflow.com/questions/43322033/create-database-on-docker-compose-startup

**Comment by dennyabrain** [comment]
I had some difficulty with getting the `entrypoint.sh` script running and also npm not installing anything, so when the server begins, it crashes since express (or rather) anything is not installed.
My current status is that my current instructions to make things work are here
https://github.com/tattle-made/Uli/wiki/Setup-Uli-on-Linux-for-Chrome
https://github.com/tattle-made/Uli/wiki/Setup-Uli-on-Linux-for-Firefox

Lets run it on your linux machine @duggalsu and see if atleast on linux its seamless. Then we'll also try to make it work on windows. Aatman can give his instructions and i can try running it on my windows machine

**Comment by aatmanvaidya** [comment]
This issue will be continued forward here - https://github.com/tattle-made/Uli/issues/397
