### ISSUE TITLE
Automate testing of Uli

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#374]
**Is your feature request related to a problem? Please describe.**
We need to automate testing new and old features of the browser extension. This would involve identifying core features (like slur replacement) and writing unit tests. It would also involve writing e2e tests through some browser automation service for core features (add custom words to slur list) 

**Describe the solution you'd like**
Ideally we should be able to run `npm run test` in a github action and have all the tests be run. This might not be feasible for the e2e tests which require running things in a browser. In which case we might have to enforce running these tests on a laptop/desktop as part of the PR review process.

**Describe alternatives you've considered**
We experimented with browser automation last year to test out core features [here](https://github.com/tattle-made/Uli/tree/main/ogbv-ml-rest/automated-testing)

**Additional context**
This came out of https://github.com/tattle-made/Uli/issues/347#issuecomment-1714972985

**Comment by duggalsu** [comment]
We ideally need to have the following e2e testing setup
1. Automated Unit testing e.g. using Jest
2. Automated browser-based / client-side testing requiring GUI interaction - only feasible for Firefox using Selenium
3. API / server-side calls testing using e.g. cURL / Hoppscotch / Postman

I have created PR #377 for browser-based / client-side testing. 

We can ideally run Uli on all Chromium-based browsers and firefox. 

I have added/updated scripts for slur redaction testing for the following browsers
- Google Chrome   - script implemented but not tested due to current setup issues 
- Chromium            - tested and working
- Brave                     - not tested due to current setup issues
- Microsoft Edge    - script implemented but not tested due to current setup issues
- Firefox                   - script is currently not working and needs to be modified 
- Opera                    - implementation seems feasible but not attempted yet

**Comment by dennyabrain** [comment]
@duggalsu this looks good!
two suggestions :
1. I like how you organized code by browser. Lets focus on getting firefox and chrome tests running. we can leave the other browsers empty or with a dummy script. I think in the presence of firefox and chrome tests, those other browsers could be easily added by future contributors.
2. I agree on the assessment of 1 and 3. Atleast for now, we can setup jest and write a unit test for the slur replacement function. and lets independently evaulate how to do 3 well. Coz i was thinking that besidess curl/hoppscotch/postman, one automation friendly way to test API calls is by using axios (the http request library that the frontend is using anyway). We could write a detailed test suite for every api endpoint and most likely orchestrate it using jest itself. something to consider. We can create a new issue for it and assign @aatmanvaidya

**Comment by duggalsu** [comment]
@dennyabrain sounds good!

I've tested on Google Chrome successfully. There is only a minor tag change for maintaining chrome, chromium, and brave. So I will keep updating scripts for those. I won't be able to test brave on my end due to setup issues but others can run the tests to see if it works. Edge and Opera require more modifications so I won't focus on that.

**Comment by duggalsu** [comment]
Merged with PR #377
