### ISSUE TITLE
Upgrade gatsby for `uli-website` 

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#384]
**Is your feature request related to a problem? Please describe.**
I want to upgrade all gatsby dependencies  used in `uli-website`  

Its not as easy as just upgrading all dependencies to their latest. For instance one issue that I came up against is that the latest version of gatsby expects a latest version of gatsby-plugin-mdx. And apparently that plugin has had a major version upgrade and its involves upgrading the website code itself to use correctly. So as part of this issue, one must assess all thats needed to be changed and gives us updates here so we could do that.

**Comment by duggalsu** [comment]
This issue is now being handled with PR https://github.com/tattle-made/Uli/pull/483

- [x] All packages have been updated to latest version
- [x] `gatsby` and `react-dom` require `legacy-peer-deps`. This can only be implemented package-wide and has been addressed by adding the flag to the `.npmrc` file
  - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#updating-your-dependencies
  - https://stackoverflow.com/questions/69496618/automatic-npm-install-legacy-peer-deps-for-a-single-dependency	
  - https://docs.npmjs.com/cli/v10/using-npm/config#legacy-peer-deps
- [x] `graphql` schema changes have been handled by using `gatsby-codemods` on `index.jsx`
  - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#graphql-schema-changes-to-sort-and-aggregation-fields
- [x] `fileAbsolutePath` has been removed from `gatsby-plugin-mdx`. This has been handled by using `internal` `contentFilePath`
  - https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/
  - https://stackoverflow.com/questions/75326784/gatsby-graphql-query-no-longer-working-after-update
- [ ] MDX File rendering issues after `gatsby-plugin-mdx` updates need to be resolved, specifically pages `about`, `faq` and `research`
  - https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/
- [ ] `slug` moved within `fields` in `gatsby-plugin-mdx` now has to be handled correctly to render paths to open blogs. Currently added `gatsby-node.mjs` file for this and modified `index.jsx`
  - https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#extending-the-graphql-mdx-nodes
  - https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#introduction
  - [ ] This approach is currently omitting `localhost` path
    - https://www.paulie.dev/posts/2022/09/mdx-2-breaking-changes-and-gatsby-plugin-mdx-v4-slug/
  - [ ] This approach is currently not working as expected
    - https://github.com/gatsbyjs/gatsby/blob/master/examples/using-mdx/gatsby-node.mjs
  - [x] This plugin has the same issues as above and is also not maintained - do NOT use this
    - https://www.gatsbyjs.com/plugins/gatsby-plugin-slug/
