### ISSUE TITLE
Uli messing with typing on gmail and slack

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#404]
**Describe the bug**
I installed Uli on Brave ([Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (x86_64)](https://brave.com/latest/). After installation, the cursor kept moving to the beginning of the line with every character I typed making the writing not legible. 

**To Reproduce**
Install Uli through the extensions store: https://chrome.google.com/webstore/detail/uli/hbfmbflgailjeobfkhpdipcdmpclinki

**Expected behavior**
Uli should not interfere with typing behavior.

**Comment by aatmanvaidya** [comment]
This is a know bug was fixed in the previous release, but it didn't get fixed for chrome and brave because the release while pushing to chrome store failed, hence the bug is still there. 

We are working on it and hope to fix it `publish to chrome` bug in this coming release.

Something like this is happening right? - https://github.com/tattle-made/Uli/issues/314

**Comment by aatmanvaidya** [comment]
This issue is fixed in the recent release - https://github.com/tattle-made/Uli/releases/tag/v0.1.14
