### ISSUE TITLE
Feature request - Update uuid dependency in Uli api-server

### ISSUE THREAD

**Issue by duggalsu** [tattle-made/Uli#434]
### Is your feature request related to a problem? Please describe.

Update the `uuid` dependency version in Uli `api-server`
- https://www.npmjs.com/package/uuid

### Describe the solution you would like

There are breaking changes in the below version that have to be checked and resolved
- https://github.com/uuidjs/uuid/commit/4cf24c018cead5ebe48cb4da232b57a2345d9fb5

**Comment by Apoorv012** [comment]
Hey @duggalsu I would like to work on this issue. Could you assign this to me?

**Comment by dennyabrain** [comment]
@Apoorv012, take a look at this parent issue : https://github.com/tattle-made/Uli/issues/426
This relates to updating all dependencies. The scope of this issue is not just to update the dependencies, but also work with our team member to ensure that its not broken anything. See if you are interested in taking them all.

**Comment by duggalsu** [comment]
Closed with PR #473
