### ISSUE TITLE
Identify and Test Platform for Annotation and Data Hosting

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#463]
Context : https://github.com/tattle-made/Operations/issues/160

We need to evaluate platforms that allow our partners to annotate the slur list with metadata. 
Some expected features :  
1. Easy sign up and login flow
2. Should work on phone
3. Users should be able to see annotations done by others (this is non standard feature for an annotation tool afaik)
4. Should be a managed service. We don't have engineering resources to share for this. So self hosted solutions are a no go as well.

**Comment by aatmanvaidya** [comment]
A blog from LSE - https://blogs.lse.ac.uk/impactofsocialsciences/2014/05/05/fork-merge-crowdsourcing-data-curation/
list few tools like:
- EpicCollect - https://five.epicollect.net/

**Comment by dennyabrain** [comment]
Great find. 
"Free and easy-to-use mobile data-gathering platform." I think we can add "mobile" as a requirement. Could help us understand user requirements with this issue better https://github.com/tattle-made/Uli/issues/255

**Comment by dennyabrain** [comment]
@aatmanvaidya is around till end of day today, I'll take over after that and have a final evaluation of which tool we should go ahead with by Wednesday Nov 8.

**Comment by aatmanvaidya** [comment]
| **Tool**                              | **Supported On** | **Sign Up/Login**           | **Open Source**                                                        | **Description**                                                                                                                                                                                                                             | **Recommendation** |
|---------------------------------------|------------------|-----------------------------|------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|
| Google Sheets                         | PC/Mobile        | easy                        | No                                                                     | I feel that the since there will be no UI (to select options in checkbox format etc), annotation could be a bit messy to make sense                                                                                                         | 3.5/5              |
| [Airtable](https://www.airtable.com/) | PC/Mobile        | easy (via google supported) | No - but we can test its open source alternative - https://nocodb.com/ | We can create a grid view, where there will be a spreadsheet like option to add metadata for slurs, the best part is, each column can be interactive, meaning we can add checkboxes and radio button making it easeir for users to annotate | 4.5/5              |
|                                       |                  |                             |                                                                        |                                                                                                                                                                                                                                             |                    |

I found few open-source tools, but they needed some tech setup from our side and then I think, hosting was also required, which is a no-go for us, for ex - https://github.com/doccano/doccano, https://github.com/koaning/bulk

**Comment by dennyabrain** [comment]
Take a call on monday.

**Comment by dennyabrain** [comment]
Another tool to  evaluate - https://www.kobotoolbox.org/pricing/

**Comment by dennyabrain** [comment]
We'll need to setup the platform in a state that its usable for the contributors by end of this week. Our first sync event is on Nov 27 but best to have it ready before we leave for the IRL trip.

**Comment by dennyabrain** [comment]
@aatmanvaidya has made a google sheet where this will happen. He'll walk us through it today on the planning call. most likely one of us would be incharge of talking people through it on the open call since aatman might be unavailable then.
